# Generated by Django 2.2 on 2021-04-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0004_auto_20210413_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
